Increase Size of Notified Pokemon
Glennmen/PMSF pull request #53
Opened 2018-01-04 15:50 UTC by Falaris01

Added the ability to scale the size of notified pokemon based on IV / Level / Pokemon notification settings.

![image](https://user-images.githubusercontent.com/29790503/34571593-3a6391b8-f16f-11e7-8b98-e9534a9c6e02.png)

![image](https://user-images.githubusercontent.com/29790503/34571580-2f6c3940-f16f-11e7-85b4-72919d153859.png)

2018-01-05 08:25 UTC, Falaris01 commented
Travis failed at git clone for whatever reason...

Is there a way to make it re-try now?

2018-01-05 08:44 UTC, Glennmen commented
@Falaris01 I manually restarted Travis, there are some errors that need to be fixed.

2018-01-05 12:59 UTC, Falaris01 commented
Ok got them fixed :)

2018-01-05 23:40 UTC, 123FLO321 commented
This does not cover `Notify of Rarity`
Is that intentional?

2018-01-05 23:43 UTC, 123FLO321 commented
And If you click on them they're not in front any longer.
That's not necessarily a problem of this PR but would be nice and probably easy to fix.

2018-01-06 16:24 UTC, Falaris01 commented
Thanks, I actually missed rarity notification as I used to have that disabled by default :)

2018-01-06 17:02 UTC, Falaris01 commented
> And If you click on them they're not in front any longer.That's not necessarily a problem of this PR but would be nice and probably easy to fix.

Not sure if it's desired. While it is indeed very easy, a short test showed it's shortcomings.

With the increased icon size of notified pokemon the smaller icons might get stuck behind those and end up making the user need to zoom in to see what's behind.

![image](https://user-images.githubusercontent.com/29790503/34641951-c1762b32-f30b-11e7-99c2-75f4522f435d.png)

2018-01-07 00:31 UTC, 123FLO321 commented
True maybe. 
But it worse the other way around since larger ones are probably more important

2018-01-07 08:48 UTC, Falaris01 commented
True, it might only be an issue with the safe icons anyway and could be submitted in another PR to try the changes out.

2018-01-07 17:33 UTC, Glennmen requested changes

2018-01-07 17:33 UTC, Glennmen commented on static/js/map.common.js
> +function getIv(atk, def, sta) {
This function already exists in map.js, you should be able to call it.

2018-01-08 21:08 UTC, Falaris01 commented
Thanks for pointing that out. 

I reworked it a little, it now adds to iconSize instead of using a new var.

2018-01-08 22:06 UTC, Falaris01 commented
Sorry for the mess, I'll work this out and add another PR once I'm done

2018-01-08 22:06 UTC, closed without merging