Add option to link to Worldopole
Glennmen/PMSF pull request #68
Opened 2018-01-21 18:02 UTC by 123FLO321

Add an option that adds a "Full Stats" button in stats, that links to Wordlopole.

2018-01-21 18:33 UTC, iroken222 commented
Did u mean to do this on develop? Glennmen said he would approve PRs not on develop?

2018-01-21 18:38 UTC, 123FLO321 commented
@iroken222 Yes i did. Changed now

2018-01-22 19:26 UTC, davidrhino commented
I would like to see us move away from using the <center> tag in HTML as its been deprecated since html 4.  I plan on cleaning it up in all of our codebase as we go forward but definitely could start here. Instead you can target the switch-container and give it text-align:center;

So basically instead of 
`
<div class="switch-container">
<div><center><a href="<?= $worldopoleUrl ?>">Full Stats</a></center></div>
</div>
`
`
<div class="switch-container full-stats">
      <a href="<?= $worldopoleUrl ?>">Full Stats</a>
</div>
`
Then in the scss files add
`
.full-stats{
text-align:center;
}
`

This is a much more modern way of handling this solution as center is frowned upon in the web community.

2018-01-22 19:27 UTC, iroken222 commented
I would like to see us move away from using the <center> tag in HTML as its been deprecated since html 4.  I plan on cleaning it up in all of our codebase as we go forward but definitely could start here. Instead you can target the switch-container and give it text-align:center;

So basically instead of 
```
<div class="switch-container">
<div><center><a href="<?= $worldopoleUrl ?>">Full Stats</a></center></div>
</div>
```

```
<div class="switch-container full-stats">
      <a href="<?= $worldopoleUrl ?>">Full Stats</a>
</div>
```
Then in the scss files add
```
.full-stats{
text-align:center;
}
```

This is a much more modern way of handling this solution as center is frowned upon in the web community.

2018-01-28 12:53 UTC, peterchabs commented on pre-index.php
> +                    <div><center><a href="<?= $worldopoleUrl ?>">Full Stats</a></center></div>
I feel just the blue hyperlink `Full Stats` is a bit uninviting and easily overlooked, perhaps when enabled could trigger the Worldopole Icon along with it? (Or icon of choice)
Using on my map, no issues.

2018-01-28 16:11 UTC, hammydown4325 requested changes
Overall very good just add the extra = to prevent the type conversion and its good to merge.

2018-01-28 16:11 UTC, iroken222 commented on pre-index.php
> +            if ($worldopoleUrl != "") {
Change this to !== to prevent php type conversion

2018-02-11 20:38 UTC, merged